name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated version
      with:
        python-version: '3.10'  # Use a more recent stable version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt pytest  # Ensure pytest is installed

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure deployment happens only if tests pass

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} "
          cd /home/ec2-user/fastapi_project &&
          git pull origin main &&
          source venv/bin/activate &&
          pip install -r requirements.txt &&
          sudo systemctl restart fastapi-service
        "
